#!/bin/sh

MKDIRS="mkdir -p"
AUTODOC=/usr/local/bin/autodoc
AUTODOC_FLAGS="-copydocs -timestamp -allclasses"
AUTODOC_FORMAT=html
export AD_COPYRIGHT="Mac GPG Project"

# Expects one argument, the install path
if [ $# -eq 0 ] ; then \
    echo "Needs 2 args: action and path where to install documentation"
    echo "If action is clean, deletes path and its content"
    exit 1
fi

if [ $# -eq 1 ] ; then \
    ACTION=
    PUBLIC_DOC_INSTALLDIR=$1
else
    ACTION=$1
    PUBLIC_DOC_INSTALLDIR=$2
fi

# We need to write down file names here
AUTODOC_FILES="GPGContext.h GPGData.h GPGEngine.h GPGExceptions.h GPGKey.h GPGKeyGroup.h GPGKeySignature.h GPGObject.h GPGOptions/GPGOptions.h GPGPrettyInfo.h GPGSignature.h GPGSubkey.h GPGTrustItem.h GPGUserID.h GPGRemoteKey.h GPGRemoteUserID.h GPGSignatureNotation.h"
AUTODOC_DOCDIR="$PUBLIC_DOC_INSTALLDIR"
OTHER_FILES="IntroMacGPGME.html"

OTHER_AUTODOC_FLAGS="-typedirs -allclasses -combine -force -nosingles"

ALL_AUTODOC_FLAGS="$AUTODOC_FLAGS $OTHER_AUTODOC_FLAGS"

if [ "$ACTION" = "clean" ] ; then \
    rm -rf "$PUBLIC_DOC_INSTALLDIR" ; \
    exit 0
fi

# If autodoc is not installed, we quit without any error
if [ ! -x "$AUTODOC" ] ; then \
    echo "$AUTODOC not found. Documentation can not been generated."
    exit 0
fi

echo "Creating documentation in $PUBLIC_DOC_INSTALLDIR"
$MKDIRS "$PUBLIC_DOC_INSTALLDIR"
$AUTODOC $ALL_AUTODOC_FLAGS -format $AUTODOC_FORMAT -dest "$AUTODOC_DOCDIR" $AUTODOC_FILES

# Let's also install files which are not generated by autodoc
cp -pR $OTHER_FILES "$PUBLIC_DOC_INSTALLDIR/"
